version: "3"
services:
  bitcoind:
    restart: unless-stopped
    container_name: bitcoind
    image: sosthenebitcoin/bitcoind_$NETWORK:latest
    ports:
      - "47382:47382"
      - "39388:39388"
    volumes:
      - "bitcoin_datadir:/data"
  eps:
    depends_on:
      - bitcoind
    restart: unless-stopped
    container_name: eps
    image: sosthenebitcoin/eps:latest
    command: "python3 launch.py $MASTERPUBKEY"
    ports:
      - "50002:50002"
    volumes:
     #- "bitcoin_datadir:/data/.bitcoin"
      - "eps_datadir:/data"
volumes:
  bitcoin_datadir:
  eps_datadir:
